FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY target/BookStoreManager-0.0.1-SNAPSHOT.jar /app/BookStoreManager-0.0.1-SNAPSHOT.jar
EXPOSE 8885
CMD ["java", "-jar", "BookStoreManager-0.0.1-SNAPSHOT.jar"]
